/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Model.HashUtil;
import Persistencia.Conexao;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author WPCALE
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jtdados = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jtcript = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jtdecrip = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("Pegar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Criptografar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Pegar do banco");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Criar Chave");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Compar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtdados)
                    .addComponent(jtcript)
                    .addComponent(jtdecrip)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 383, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtdados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtcript, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(42, 42, 42)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtdecrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton5)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jtdados.setText("");
        String placaMae = "";
        String hd = "";
        String nomePC = "";

        try {

            // ==========================
            // PLACA MÃE
            // ==========================
            Process p = Runtime.getRuntime().exec("wmic baseboard get serialnumber");

            BufferedReader br = new BufferedReader(new InputStreamReader(p.getInputStream()));

            String linha;

            while ((linha = br.readLine()) != null) {

                linha = linha.trim();

                if (!linha.equals("") && !linha.equalsIgnoreCase("SerialNumber")) {
                    placaMae = linha;
                    break;
                }
            }

            br.close();

            // ==========================
            // HD
            // ==========================
            p = Runtime.getRuntime().exec("wmic diskdrive get serialnumber");

            br = new BufferedReader(new InputStreamReader(p.getInputStream()));

            while ((linha = br.readLine()) != null) {

                linha = linha.trim();

                if (!linha.equals("") && !linha.equalsIgnoreCase("SerialNumber")) {
                    hd = linha;
                    break;
                }
            }

            br.close();

            // ==========================
            // NOME DO COMPUTADOR
            // ==========================
            nomePC = System.getenv("COMPUTERNAME");

            // ==========================
            // CONCATENAÇÃO FINAL
            // ==========================
            jtdados.setText(nomePC+"-"+placaMae+"-"+ hd );

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, ex.getMessage());

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String cripto=jtdados.getText().trim();
        jtcript.setText(HashUtil.sha256(cripto));

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 
String banco="";
String pc="";











        
    String sql = "SELECT thumb FROM thumb WHERE cod = ?";

    try (Connection conn = Conexao.conectar();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setInt(1, 1);

        try (ResultSet rs = pstmt.executeQuery()) {

            if (rs.next()) {

              
          jtdecrip.setText(rs.getString("thumb"));
             banco=rs.getString("thumb");
    
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }   catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String valor=jtcript.getText().trim();
int codigo=1;


        ///salvar no banco
         String sql =
            "UPDATE thumb SET thumb=?"
            + "WHERE cod=?";
        int registros;

    try (Connection conn = Conexao.conectar();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        int i = 1;
        pstmt.setString(1, valor);
        
        pstmt.setInt(2, codigo);
       

        registros = pstmt.executeUpdate();
        if(registros == 1){
        
        JOptionPane.showMessageDialog(this, "Salvo");
        };
        
        
    }   catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

 // return registros == 1;



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        jtdados.setText("");
//        String placaMae = "";
//        String hd = "";
//        String nomePC = "";
//
//        String pc="";
//        String banco="";
//        try {
//
//            // ==========================
//            // PLACA MÃE
//            // ==========================
//            Process p = Runtime.getRuntime().exec("wmic baseboard get serialnumber");
//
//            BufferedReader br = new BufferedReader(new InputStreamReader(p.getInputStream()));
//
//            String linha;
//
//            while ((linha = br.readLine()) != null) {
//
//                linha = linha.trim();
//
//                if (!linha.equals("") && !linha.equalsIgnoreCase("SerialNumber")) {
//                    placaMae = linha;
//                    break;
//                }
//            }
//
//            br.close();
//
//            // ==========================
//            // HD
//            // ==========================
//            p = Runtime.getRuntime().exec("wmic diskdrive get serialnumber");
//
//            br = new BufferedReader(new InputStreamReader(p.getInputStream()));
//
//            while ((linha = br.readLine()) != null) {
//
//                linha = linha.trim();
//
//                if (!linha.equals("") && !linha.equalsIgnoreCase("SerialNumber")) {
//                    hd = linha;
//                    break;
//                }
//            }
//
//            br.close();
//
//            // ==========================
//            // NOME DO COMPUTADOR
//            // ==========================
//            nomePC = System.getenv("COMPUTERNAME");
//
//            // ==========================
//            // CONCATENAÇÃO FINAL
//            // ==========================
//            jtdados.setText(nomePC+"-"+placaMae+"-"+ hd );
//            
//            pc=HashUtil.sha256(nomePC+"-"+placaMae+"-"+ hd) ;
//
//        } catch (Exception ex) {
//
//            JOptionPane.showMessageDialog(null, ex.getMessage());
//
//        }
//        /////////////////////////////
//        ///
//        ///pegar banco
//String sql = "SELECT thumb FROM thumb WHERE cod = ?";
//
//    try (Connection conn = Conexao.conectar();
//         PreparedStatement pstmt = conn.prepareStatement(sql)) {
//
//        pstmt.setInt(1, 1);
//
//        try (ResultSet rs = pstmt.executeQuery()) {
//
//            if (rs.next()) {
//
//              
//         // jtdecrip.setText(rs.getString("thumb"));
//             banco=rs.getString("thumb");
//    
//            }
//            
//        } catch (SQLException ex) {
//            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//    }   catch (Exception ex) {
//            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//       
//    
//    if(pc.equals(banco)){
//      JOptionPane.showMessageDialog(null,"São iguais PC: "+pc+ " - Banco: "+banco);
//    
//    }else{
//    
//     JOptionPane.showMessageDialog(null,"MAO São iguais PC: "+pc+ " - Banco: "+banco);
//    }
//
//            
//
//






















        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 jtdados.setText("");
        String placaMae = "";
        String hd = "";
        String nomePC = "";

        String pc="";
        String banco="";
        try {

            // ==========================
            // PLACA MÃE
            // ==========================
            Process p = Runtime.getRuntime().exec("wmic baseboard get serialnumber");

            BufferedReader br = new BufferedReader(new InputStreamReader(p.getInputStream()));

            String linha;

            while ((linha = br.readLine()) != null) {

                linha = linha.trim();

                if (!linha.equals("") && !linha.equalsIgnoreCase("SerialNumber")) {
                    placaMae = linha;
                    break;
                }
            }

            br.close();

            // ==========================
            // HD
            // ==========================
            p = Runtime.getRuntime().exec("wmic diskdrive get serialnumber");

            br = new BufferedReader(new InputStreamReader(p.getInputStream()));

            while ((linha = br.readLine()) != null) {

                linha = linha.trim();

                if (!linha.equals("") && !linha.equalsIgnoreCase("SerialNumber")) {
                    hd = linha;
                    break;
                }
            }

            br.close();

            // ==========================
            // NOME DO COMPUTADOR
            // ==========================
            nomePC = System.getenv("COMPUTERNAME");

            // ==========================
            // CONCATENAÇÃO FINAL
            // ==========================
            jtdados.setText(nomePC+"-"+placaMae+"-"+ hd );
            
            pc=HashUtil.sha256(nomePC+"-"+placaMae+"-"+ hd) ;

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, ex.getMessage());

        }
        /////////////////////////////
        ///
        ///pegar banco
String sql = "SELECT thumb FROM thumb WHERE cod = ?";

    try (Connection conn = Conexao.conectar();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setInt(1, 1);

        try (ResultSet rs = pstmt.executeQuery()) {

            if (rs.next()) {

              
         // jtdecrip.setText(rs.getString("thumb"));
             banco=rs.getString("thumb");
    
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }   catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    
    if(pc.equals(banco)){
      JOptionPane.showMessageDialog(null,"São iguais PC: "+pc+ " - Banco: "+banco);
    
    }else{
    
     JOptionPane.showMessageDialog(null,"MAO São iguais PC: "+pc+ " - Banco: "+banco);
    }

            




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField jtcript;
    private javax.swing.JTextField jtdados;
    private javax.swing.JTextField jtdecrip;
    // End of variables declaration//GEN-END:variables
}
